CREATE TABLE CUSTOMER (
  ID            INT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME    VARCHAR(255),
  LAST_NAME     VARCHAR(255),
  EMAIL_ADDRESS VARCHAR(255)
);;


CREATE TABLE ADDRESS (
  ID          INT AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_ID INT,
  STREET      VARCHAR(255),
  CITY        VARCHAR(255),
  COUNTRY     VARCHAR(255),
  CONSTRAINT ADDRESS_CUSTOMER_REF FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID)
);;